BlackJack 구현
eom-tae-in/java_black_jack pull request #3
Opened 2023-06-06 00:24 UTC by eom-tae-in

2023-06-07 01:43 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +    public void start() {
메서드는 15라인 넘지 않도록 변경하기

2023-06-07 01:44 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +    private final CardDeck cardDeck = new CardDeck();
이렇게 선언 해줄 때 문제점은 없을까?

2023-06-07 01:44 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +    private final OutputView outputView = new OutputView();
생성자 주입과 필드 선언에 있어서 뭐가 다를까?
서로 어떤 장점이 있는지 설명해줄래?

2023-06-07 02:34 UTC, sosow0212 requested changes
태인아 전반적으로 코멘트 확인해보고 구조적으로 다시 설계하는 게 좋을 것 같아
굿굿 고생했어

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        String result = "";
이 result라는 comment를 객체로 관리하면 어떤 일이 생길까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        int result = compareNumber(dealer.getSum(), player.getSum());
메서드 네이밍은 동사로 시작하기

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +    void firstDraw(Dealer dealer, Players players) {
메서드 이름은 동사로 시작하기

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        if ((dealerSum > playerSum && dealerSum <= 21) || playerSum > 21) {
if문 안에 분기가 어떤 것을 의미하는 것일까?
의미를 부여해줄까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Value.java
> +    private int otherNumber;
1. 이 otherNumber는 A일때 1, 11에 해당하는 경우에만 사용하는 것 같은데, `CardValue` 객체와 이 객체를 조금 바꿔보는 건 어떨까?

2. ohterNumber를 살리려면 네이밍을 바꿔보는 건 어떨까

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Value.java
> +    public Value(final String value, int number) {
이 생성자로 초기화 했을 때, `getOtherNumber()`를 호출하면 어떤 일이 생길까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/CardDeck.java
> +import java.util.*;
import에 와일드카드는 지양하기
https://google.github.io/styleguide/javaguide.html

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/CardDeck.java
> +                .forEach(cardShape -> Arrays.stream(CardValue.values())
1. 접근 제어자는 어디갔어?

2. `ready()`와 함께 이 generate()라는 행위는 CardDeck에 있어서 항상 동일한 것 같은데, 정적 팩토리 메서드로 카드 덱을 만들어주고 생성까지 해주는 로직으로 바꿔보면 어떨까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/CardDeck.java
> +    private final Queue<Card> cardDeck = new LinkedList<>();
생성자를 안 쓰고 이렇게 만든 이유가 있을까?
이렇게 했을 때 어떤 문제점이 있을까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/UserDeck.java
> +    private final List<Card> cards = new ArrayList<>();
얘도 생성자를 안 쓴 이유가 있을까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/UserDeck.java
> +        for (Card c : cards) {
c가 의미하는 건 뭘까?
변수명은 축약 금지

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/UserDeck.java
> +    public int findSpecialIndex() {
`UserDeck` 클래스에서만 사용하는 메서드인데 public으로 열어둔 이유가 있어?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/UserDeck.java
> +                .filter(i -> cards.get(i).getValue().equals(ACE))
i가 의미하는 건 뭘까?

`cartds.get(i).getValue().equals(...)`보다는 객체한테 책임을 주는게 어떨까?
UserDeck의 역할이 아닌 Card의 역할 아닐까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/UserDeck.java
> +                .findAny().orElse(NOT_EXIST_SPECIAL);
1. 객체지향 생활체조 4번 참고

2. `orElse`, `orElseThrow`의 차이는 무엇일까?
- 매직넘버 `-1`을 반환하는 건 버그를 유발할 수 있다. (from. 좋은 코드, 나쁜 코드)

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/UserDeck.java
> +        if (specialSum <= 21) {
매직넘버 상수처리 해주기

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/UserDeck.java
> +        int specialSum = sum - card.getNumber() + card.getOtherNumber();
`specialSum`이라는 변수명도 그렇고 전반적으로 `special`이라는 용어를 많이 사용하는데, 흐름상 파악은 가능하지만, 사용하려면 다른 메서드 명을 조금 더 명확하게 해주면 special의 의미를 더 파악하기 쉽지 않을까?

이를테면 여기선 `sum - card.getNumber() + card.getOtherNumber()`로 표현하고 있는데, sum과 otherNumber를 바꿔주면 의미가 조금 더 와닿을 것 같기도 하네

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Player.java
> +    public void drawCard(String answer) {
카드를 뽑는 행위에 두 가지 일을 하고 있네

1. y인지 아닌지 판단
2. 카드를 뽑기

여기서 1번 행위는 Player가 해야하는 행위일까?
이 1번 행위의 역할과 책임의 주체는 어떤 객체가 해야할까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Player.java
> +    public void getCard(DrawCardDto drawCardDto) {
1. 여기서 Dto는 어떤 역할을 하는 걸까?
2. 현재 Participant를 가지고 있는데, 여기서 판단할 순 없을까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Players.java
> +    List<Player> players = new ArrayList<>();
클래스 밑에 한 칸 개행 추가해주기

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Players.java
> +public class Players {
이 `Players`라는 일급 컬렉션은 어떤 역할을 하는 것일까?
일급 컬렉션을 사용할 때 장점은 무엇이고, 이 장점을 살리기 위해서 어떻게 개선할 수 있을까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Players.java
> +    public List<Player> getPlayers() {
방어적 복사란 무엇이고 왜 쓸까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Result.java
> +        this.drew = drew;
이 객체는 DTO의 역할을 하는것일까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Participant.java
> +    private final CardDeck cardDeck;
CardDeck과 UserDeck은 무엇일까?

`CardDeck`에서 카드를 배분해준다면, 전체 게임에서 CardDeck은 하나로 관리하고, 여기서 카드를 배분해야할 것 같은데

Participant 별로 `CardDeck`을 가지고 있다면, 참여자들이 같은 카드를 가질 수도 있을까?

이걸 의도한게 아니라면 코멘트 고고~

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Participant.java
> +    public static Participant Dealer(UserDeck userDeck, CardDeck cardDeck) {
1. `Dealer`라는 메서드의 이름은 무엇일까?
딜러를 이렇게 만들어주는 것이 좋을까?

2. `UserDeck`, `CardDeck`은 이미 Participant 안에 있는데, 다른 UserDeck, CardDeck을 받는 이유는 무엇일까?

3. 다르게 개선할 순 없을까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Participant.java
> +        return name.getName();
어떤 건 this가 붙고 어떤 건 this가 없는데 전체 클래스에 대해서 통일하면 좋을듯

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/DrawCardDto.java
> +public class DrawCardDto {
1. 이 Dto가 하는 역할은 무엇일까?
2. Dto인데 Domain패키지에 있어도 될까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Name.java
> +    public Name(final String name) {
1. 이름에 공백이 들어오면 어떻게 될까?
2. 원시값 포장을 사용하면 좋은 점이 무엇일까?
3. 이 `Name` 객체가 할 수 있는 일이 많을 것 같은데, 역할의 분배를 다시 해줘볼까?
4. 어떤 건 파라미터에 final이 붙고 어떤 건 안 붙는데 의도한 것일까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/domain/Dealer.java
> +        return participant.getSum() <= 16;
16은 무엇을 의미하는 수야?

2023-06-07 02:34 UTC, sosow0212 commented on src/test/java/domain/CardDeckTest.java
> +    void DrawCardFirst() {
메서드명과 DisplayName에서 표현하는 것이 다른데, 어떤 것이 맞을까?

1. 카드를 처음 뽑는다.
2. 카드 덱에서 처음 카드를 뽑을 경우 2장을 뽑는다.

테스트 메서드 명을 짓는 방법은 많은데 나는 이렇게 쓸 것 같아.
`returns_two_cards_when_draw_from_card_deck_at_first`
더 좋게 할 순 있긴 할듯 (테스트 네이밍은 여러가지가 있으니 마음에 드는 걸로 선택하고 일관적으로 유지하면 좋을 것 같아 + 메서드 명 그대로 테스트 메서드 명을 지으면 유지보수 측면에서 메서드가 바뀌면 테스트 메서드명도 바꿔야하니 좋지 않으니 행위에 대해 네이밍 해주면 어떨까?)

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/view/OutputView.java
> +    public void AskMore(Player player) {
1. `View`에서 `Player`에 무엇이 있는지를 알아야할까?

2. Player가 바뀐다면, View도 바뀔까?

3. 이를 개선하기 위한 방법은 무엇이 있을까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/view/OutputView.java
> +            sb.append(card.getValue()).append(card.getShape()).append(", ");
객체지향 생활체조 4번 참고

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/view/OutputView.java
> +    private final StringBuilder sb = new StringBuilder();
sb가 의미하는 건 무엇일까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/view/OutputView.java
> +    public void AskName() {
메서드 명 컨벤션 확인해보기
`askName()` 이 맞지 않을까?

2023-06-07 02:34 UTC, sosow0212 commented on src/test/java/domain/PlayerTest.java
> +        DrawCardDto drawCardDto = new DrawCardDto(new Card(new Shape("스페이드"), new Value("6", 6)),
1.`DrawCardDto`도 그렇고 다른 객체도 계속 만들어서 사용하는데 `Test Fixture`란 무엇일까?

2023-06-07 02:34 UTC, sosow0212 commented on src/test/java/domain/UserDeckTest.java
> +    void CalculateSumUserDeck() {
메서드명을 지을 때 첫 글자는 대문자일까? 소문자일까?

2023-06-07 02:34 UTC, sosow0212 commented on src/test/java/domain/UserDeckTest.java
> +    @DisplayName("유저 덱에 Ace가 존재하면 해당 인덱스를 반환하고 없으면 -1을 반환한다.")
해당 객체에도 리뷰를 남겼지만, -1 같은 매직넘버를 반환하는 건 좋지 않은 습관이고, 버그를 유발할 수 있으니 다르게 바꾸는 건 어떨까?

2023-06-07 02:34 UTC, sosow0212 commented on src/main/java/BlackJack.java
> +    public static void main(String[] args) {
작동이 제대로 안 되는 것 같은데 확인해볼래?

n을 입력할 때까지 카드를 계속 더 받을 수 있고, 어떤 카드를 받았는지 볼 수가 없어

2023-06-08 10:27 UTC, eom-tae-in commented on src/main/java/BlackJack.java
> +    public static void main(String[] args) {
내가 빨리 만드는거에 몰두하다보니 출력 조건을 안 지킨 게 있네 ㅠㅠ 
다시 수정할게

2023-06-11 16:28 UTC, eom-tae-in commented on src/main/java/controller/Controller.java
> +    private final OutputView outputView = new OutputView();
생성자 주입은 생성자 호출 시점에 딱 1번만 호출되는 것이 보장되어 값을 세팅 한 이후 변경할 수 없다는 장점이 있고 필드 선언은 스프링에서 @Autowired하나로 의존성 주입을 할 수 있어 편하게 사용할 수 있다는 장점이 있어. 하지만 필드 주입은 순수 자바코드로는 테스트를 진행하지 못한다는 단점이 있어.

2023-06-11 16:28 UTC, eom-tae-in commented on src/main/java/controller/Controller.java
> +    private final CardDeck cardDeck = new CardDeck();
필드 주입은 인스턴스 생성 이후에 이루어져서 필요한 의존성을 미리 알고 있어야하는 문제가 있지. 저번에 이야기해준대로 스프링도 자바코드로 개발되었으니까 이 부분은 생성자를 통해 인스턴스를 생성하도록 수정할게

2023-06-11 16:29 UTC, eom-tae-in commented on src/main/java/controller/Controller.java
> +    public void start() {
수정하겠습니다. ㅎㅎ

2023-06-11 16:29 UTC, eom-tae-in commented on src/main/java/controller/Controller.java
> +    void firstDraw(Dealer dealer, Players players) {
확인

2023-06-11 16:34 UTC, eom-tae-in commented on src/main/java/controller/Controller.java
> +        String result = "";
객체로 관리하면 플레이어가 추가로 카드를 받았는지 안받았는지, 받았다면 몇장을 받았는지를 알 수 있게 되는거 같아

2023-06-11 16:35 UTC, eom-tae-in commented on src/main/java/controller/Controller.java
> +        int result = compareNumber(dealer.getSum(), player.getSum());
확인

2023-06-11 16:37 UTC, eom-tae-in commented on src/main/java/controller/Controller.java
> +        if ((dealerSum > playerSum && dealerSum <= 21) || playerSum > 21) {
메서드로 분리해서 메서드명을 통해 의미를 부여해볼게

2023-06-11 16:39 UTC, eom-tae-in commented on src/main/java/domain/CardDeck.java
> +    private final Queue<Card> cardDeck = new LinkedList<>();
우선 테스트를 할 때 문제가 있을 거 같아. 다른 문제점은 한번 찾아볼게

2023-06-11 16:57 UTC, eom-tae-in commented on src/main/java/domain/CardDeck.java
> +                .forEach(cardShape -> Arrays.stream(CardValue.values())
1. 사실 이 부분은 내가 한번 빼보고 문제가 없어서 그대로 둔 거 같아. 기능만 급하게 만들고 이런 부분을 많이 놓쳤던 거 같아. 리뷰보면서 꼼꼼히 수정할게 쏘리...ㅎㅎ
2. 카드덱이 생성될 때 어차피 52장의 shuffle된 카드가 있도록 하는 거니까 정적팩토리 메서드안에 생성 로직까지 해주도록 만들면 훨씬 좋을거 같아.

2023-06-11 16:59 UTC, eom-tae-in commented on src/main/java/domain/Dealer.java
> +        return participant.getSum() <= 16;
딜러가 추가로 카드를 받는 것에 대한 유무를 판단하는 수야. 매직넘버는 상수처리 했어야 했는데 수정할게.

2023-06-11 17:04 UTC, eom-tae-in commented on src/main/java/domain/DrawCardDto.java
> +public class DrawCardDto {
1. 처음 카드를 받을 때는 2장, 이후 추가 카드를 받을 때는 1장을 받는데 받은 카드를 플레이어나, 딜러의 덱에 더할 때 하나의 메서드를 통해 처리하는 방법을 생각하다 Dto를 추가했어. DrawCardDto가 하는 역할은 받은 카드를 플레이어나 딜러의 덱 객체에 전달하는 역할을 해
2. 음.... 그러게??

2023-06-11 17:15 UTC, eom-tae-in commented on src/main/java/domain/Name.java
> +    public Name(final String name) {
1. 예외처리를 해야해서 적절한 에외를 발생시켜야 할 거 같아
2. 원시값 포장을 하면 해당 필드들을 따로 관리하며 필드에 대한 검증로직을 분리할 수 있어서 유지보수하기 편해지는 장점이 있어
3. 확인
4. 따로 의도를 하진 않았던 거 같아....

2023-06-11 17:25 UTC, eom-tae-in commented on src/main/java/domain/Participant.java
> +    private final CardDeck cardDeck;
1. CardDeck과 UserDeck은 무엇일까?
-> CardDeck은 전체 52장의 카드 덱이고 UserDeck은 플레이어, 딜러의 개인 덱이야
2. CardDeck은 카드를 요청하면 랜덤하게 뽑아주는데 이 뽑아준 카드를 가져가는 것을 플레이어, 딜러가 하도록 하게 만들려고 했어. 사실 draw메서드로 카드를 가져올 때 파라미터로 CardDeck을 넘겨도 되지만 객사오를 읽을 때 파라미터를 통해서 추가로 구체적인 정보를 요할 때 사용한다는 내용을 읽었어. 즉 CardDeck을 파라미터로 받는 것이 구체적이게 보이진 않았어. 그래서 참가자(플레이어, 딜러)가 CardDeck에 대해 알도록 설계했어.

2023-06-11 17:37 UTC, eom-tae-in commented on src/main/java/domain/Participant.java
> +    public static Participant Dealer(UserDeck userDeck, CardDeck cardDeck) {
1. Dealer라는 메서드명을 makeDealer, createDealer으로 작성했다면 더 좋았을 거 같네, 음 생성자로 new Participant("딜러", userDeck, cardDeck) 이런식으로 작성하는 것이 딜러의 Participant 인스턴스를 생성하는 방법 중 최선의 방법은 아니라는 생각이 들었어. 
2. 음 이거는 내가 리뷰를 제대로 이해한지 모르겠는데 나는 기본 플레이어들은 생성자로 인스턴스를 생성하도록 했고 딜러는 정적 팩토리 메서드를 사용해서 인스턴스를 생성하도록 했어
3. 생각 해보고 코드에 적용해볼게

2023-06-11 17:38 UTC, eom-tae-in commented on src/main/java/domain/Participant.java
> +        return name.getName();
확인

2023-06-11 17:40 UTC, eom-tae-in commented on src/main/java/domain/Player.java
> +    public void drawCard(String answer) {
한 가지 일만 하도록 수정할게
이래서 result를 객체로 관리하라고 한 거구나 
Player가 대답을 했는데 검증을 Player가 하는 것은 잘못된 역할 분담이라고 생각해.
수정하도록 하겠습니다 ㅎㅎ

2023-06-11 17:58 UTC, eom-tae-in commented on src/main/java/domain/Player.java
> +    public void getCard(DrawCardDto drawCardDto) {
이거는 내가 생각이 너무 짧았던 거 같아. 무작정 체이닝이 길면 안된다는 생각으로만 이렇게 만들었던 거 같아.

2023-06-19 09:04 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        Arrays.stream(playerNames).forEach(player -> players.add(new Player(new Name(player), new ParticipantDeck())));
객체지향 생활체조 4번 참고

2023-06-19 09:06 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        dealer.getCard(cardDeck.draw());
`getCard`라는 의미는 카드를 반환하는 거야? 아니면 카드를 하나 얻는다는 의미야?
모호한 네이밍 말고 바꾸는 게 좋을듯!

2023-06-19 15:55 UTC, sosow0212 commented on src/main/java/domain/Name.java
> +    private final String name;
한 칸 개행 추가하기~

2023-06-19 15:55 UTC, sosow0212 commented on src/main/java/domain/Name.java
> +        StringValidator.validation(name);
String 예외는 여러 곳에서 발생해서 중복을 따로 뺀 거지??
굿굿~

2023-06-19 15:56 UTC, sosow0212 commented on src/main/java/domain/Participant.java
> +    public void getCard(final Card card) {
getCard 라는 네이밍은 카드를 뽑는다는 거지?
다른 네이밍은 어떨까?

2023-06-19 15:56 UTC, sosow0212 commented on src/main/java/domain/ParticipantDeck.java
> +        return Collections.unmodifiableList(cards);
방어적복사 굿

2023-06-19 15:57 UTC, sosow0212 commented on src/main/java/domain/ParticipantDeck.java
> +public class ParticipantDeck {
`ParticipantDeck` 이라는 네이밍은 참여자의 덱을 의미하는 것 같은데,
Deck이라고 명하는 건 어떨까?

만약에 DealerDeck이 생길 수도 있다면? 그러면 Deck의 역할은 중복이 되지 않을까?

2023-06-19 15:57 UTC, sosow0212 commented on src/main/java/domain/ParticipantDeck.java
> +    }
개행 추가해주기~

2023-06-19 15:59 UTC, sosow0212 commented on src/main/java/domain/ParticipantDeck.java
> +    private boolean isContainAce() {
`isContainAce` 보다는 `hasAce` 같은 네이밍은 어떨까?
`isContainedAce`가 맞나? 문법은 잘 모름 ㅋㅋ 근데 hasAce도 괜찮을듯
글구 밑에도 개행추가~

2023-06-19 16:01 UTC, sosow0212 commented on src/main/java/domain/Player.java
> +    public void addResult(final Result result) {
add는 추가해준다는 의미아닐까?
현재는 set의 의미가 강한 것 같아 (덮어씌워서)
다르게 로직을 변경하거나, 네이밍을 바꾸는 건 어떨까

2023-06-19 16:01 UTC, sosow0212 commented on src/main/java/domain/Players.java
> +public class Players {
한칸 개행을 띄워주는게 전체적인 컨벤션에 맞는 것 같아

2023-06-19 16:02 UTC, sosow0212 commented on src/main/java/domain/Results.java
> +                .filter(result -> result.getResult().equals(WIN.getResult()))
`result`가 win인지 확인하는 행위는 누가 어디서 하는 것이 좋을까?

2023-06-19 16:03 UTC, sosow0212 commented on src/main/java/domain/Results.java
> +                .filter(result -> result.getResult().equals(DRAW.getResult()))
위에 리뷰와 더불어서 만약 현재 작성한 이런 구조로 만들고 싶다면, getWin ~ getLose까지 중복 로직이 발생하네 이 부분을 줄일 수 있을 것 같아

2023-06-19 16:04 UTC, sosow0212 commented on src/main/java/dto/OnlyOneCardResponseDto.java
> +public class OnlyOneCardResponseDto {
`CardResponse`라는 네이밍은 어떨까?
지금 볼 때 OnlyOne이라는 네이밍은 필요없어보이고, Response라는 명칭이 붙었으니 Dto라는 네이밍도 중복으로 보여서

2023-06-19 16:05 UTC, sosow0212 commented on src/main/java/exception/InputBlankException.java
> +public class InputBlankException extends IllegalArgumentException{
정렬해주기

2023-06-19 16:06 UTC, sosow0212 commented on src/main/java/exception/InputBlankException.java
> +        super(message);
message를 받아서 처리를 해주는데, 그러면 다른 exception이랑 역할은 모두 같고, 네이밍만 다른 Exception인 것인가?
그렇다면 예외를 상속받아서 처리를 해주는 방법으로 바꿀 수도 있고, 메시지를 예외 클래스에서 관리하는 방법도 있을 것 같은데 뭐가 더 좋을 것 같아? 고민하고 바꿔볼래?

2023-06-19 16:07 UTC, sosow0212 commented on src/main/java/exception/InputBlankException.java
> +        super(message);
++ 예외 메시지를 어디서 갖는 것이 현재 진행중인 서비스에서 더 적합할 것 같은지 묻는거야

2023-06-19 16:11 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        Arrays.stream(playerNames).forEach(player -> players.add(new Player(new Name(player), new ParticipantDeck())));
현재 구조에서는

1. `receiveName()` 메서드를 통해서 참여자의 이름을 입력받는다.
2. `InputView`에서 이름을 입력받는 동시에 예외처리를 한다. (정제된 플레이어 네이밍)
3. 객체로 만들어준다

이렇게 진행되고 있는데, 

1. 이름의 예외를 처리해주는 부분은 어떤 객체에서 수행해야지 더 적절할까?

2023-06-19 16:12 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +    private final CardDeck cardDeck;
게임이 성공적으로 마친 후에 콘솔이 종료되지 않고, 재시작을 할 수 있다면, 카드 덱은 초기화될까?

2023-06-19 16:13 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        askName();
1. View를 static으로 만든 이유가 뭐야?
- static으로 사용했다면, 앞에 클래스 이름을 붙여주는게 조금 더 좋지 않을까? (askName이 묻는 것인지, 아니면 입력을 받기 위한 것인지 헷갈릴 수 있음)

2. static 메서드의 장단점이 무엇일까?

2023-06-19 16:14 UTC, sosow0212 commented on src/main/java/controller/Controller.java
> +        while (!player.isGameOver() && Answer.isYes(getAnswer(player.getName()))) {
while안에 조건문은 어떤 것을 의미하는 것일까?

2023-06-19 16:15 UTC, sosow0212 approved these changes
태인아 추가 코멘트 남겨놨고, 확인하고 고친 후에 다음 단계로 진행하자
처음보다 많이 좋아져서 일단 어프루브 할게
혹시 모르는 부분이나 질문사항 있으면 편하게 코멘트 남기고~
고생했다👍

2023-06-22 04:41 UTC, eom-tae-in commented on src/main/java/domain/ParticipantDeck.java
> +public class ParticipantDeck {
딜러와 플레이어의 겹치는 로직을 처리하기 위해 ParticipantDeck을 만들었어. Dealer가 지금 ParticipantDeck을 상속받고 있어서 DealerDeck에 대해서는 따로 생각하지 않아도 될 거 같아.
네이밍은 ParticipantDeck보다 Deck이 좀 더 괜찮아 보이는 거 같아. Participant를 붙였을 때와 안 붙였을 때 의미가 크게 다르지 않은 거 같으니 Dealer로 수정해야겠음

2023-06-22 04:48 UTC, eom-tae-in commented on src/main/java/domain/Participant.java
> +    public void getCard(final Card card) {
CardDeck에서 카드를 뽑아서 플레이어가 그 카드를 받는 거라고 생각해서 CardDeck에는 카드를 한 장 뽑아오는 메서드 네이밍을 draw()라고 지었어. CardDeck이 뽑은 카드를 플레이어가 받는 것이므로 getCard가 적당한 네이밍이라고 생각했어. 처음에 get Draw라고 이름을 지었는데 'CardDeck에서 뽑은 카드를 플레이어가 뽑는다.'는 로직이 의미하는 바가 올바르지  않은거 같아서 getCard로 바꿨어.

2023-06-22 18:10 UTC, merged

2023-06-23 03:10 UTC, sosow0212 commented on src/main/java/domain/ParticipantDeck.java
> +public class ParticipantDeck {
굿굿~